############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Logs"
url = "/logs"
weight = 3

# [[main]]
# weight = 4
# url = "/notes"
# name = "Notes"





# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Contacts"
url = "/contact"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3

