############# English navigation ##############

# main menu
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "关于我"
url = "/about"
weight = 2

[[main]]
name = "每月特供"
url = "/logs"
weight = 3

# 暂时隐藏
# [[main]]
# name = "货架（有点积灰了）"
# url = "/notes"
# weight = 4





# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Contacts"
url = "/contact"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3

############# Chinese navigation ##############
